-- Constituency rollout. Service is not nationwide: super admin opens areas.
-- Polling stations follow their constituency. Closed areas collect downloads and shares.

alter table profiles add column if not exists area_id text;

create table if not exists coverage_areas (
  id text primary key,
  region text not null,
  name text not null,
  lat double precision not null,
  lng double precision not null,
  open boolean not null default false,
  locked boolean not null default false,
  auto_open boolean not null default true,
  unlock_mode text not null default 'either',
  downloads_required int not null default 200,
  shares_required int not null default 40,
  downloads int not null default 0,
  shares int not null default 0,
  promo_note text not null default ''
);

create table if not exists area_members (
  user_id text primary key,
  area_id text not null,
  referred_by text,
  shares_sent int not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists area_members_area_idx on area_members (area_id);

create table if not exists area_events (
  id serial primary key,
  area_id text not null,
  kind text not null,
  detail text not null default '',
  created_at timestamptz not null default now()
);
create index if not exists area_events_area_idx on area_events (area_id, id desc);

insert into coverage_areas (
  id, region, name, lat, lng, open, locked, auto_open, unlock_mode,
  downloads_required, shares_required, promo_note
) values
  ('ayawaso-west-wuogon', 'Greater Accra', 'Ayawaso West Wuogon', 5.636, -0.151, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('okaikwei-south', 'Greater Accra', 'Okaikwei South', 5.605, -0.2, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('korle-klottey', 'Greater Accra', 'Korle Klottey', 5.558, -0.182, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('la-dade-kotopon', 'Greater Accra', 'La Dade-Kotopon', 5.569, -0.171, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('ledzokuku', 'Greater Accra', 'Ledzokuku', 5.595, -0.1, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('krowor', 'Greater Accra', 'Krowor', 5.601, -0.07, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('adentan', 'Greater Accra', 'Adentan', 5.705, -0.155, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('tema-central', 'Greater Accra', 'Tema Central', 5.669, 0.016, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('tema-east', 'Greater Accra', 'Tema East', 5.68, 0.03, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('ablekuma-central', 'Greater Accra', 'Ablekuma Central', 5.56, -0.23, false, false, true, 'either', 200, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('odododiodio', 'Greater Accra', 'Odododiodio', 5.54, -0.21, false, false, true, 'either', 200, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ga-south', 'Greater Accra', 'Ga South', 5.56, -0.3, false, false, true, 'either', 260, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ga-west', 'Greater Accra', 'Ga West', 5.7, -0.28, false, false, true, 'either', 180, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ningo-prampram', 'Greater Accra', 'Ningo-Prampram', 5.73, 0.09, false, false, true, 'either', 280, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('shai-osudoku', 'Greater Accra', 'Shai-Osudoku', 5.85, 0.05, false, false, true, 'either', 160, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ada', 'Greater Accra', 'Ada', 5.78, 0.63, false, false, true, 'either', 240, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('subin', 'Ashanti', 'Subin', 6.69, -1.624, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('manhyia-south', 'Ashanti', 'Manhyia South', 6.705, -1.615, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('bantama', 'Ashanti', 'Bantama', 6.7, -1.64, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('asokwa', 'Ashanti', 'Asokwa', 6.67, -1.61, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('suame', 'Ashanti', 'Suame', 6.73, -1.63, false, false, true, 'either', 280, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ejisu', 'Ashanti', 'Ejisu', 6.73, -1.45, false, false, true, 'either', 200, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('obuasi-east', 'Ashanti', 'Obuasi East', 6.2, -1.67, false, false, true, 'either', 140, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bekwai', 'Ashanti', 'Bekwai', 6.45, -1.58, false, false, true, 'either', 240, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('mampong', 'Ashanti', 'Mampong', 7.06, -1.4, false, false, true, 'either', 200, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('takoradi', 'Western', 'Takoradi', 4.901, -1.759, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('sekondi', 'Western', 'Sekondi', 4.935, -1.714, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('essikado-ketan', 'Western', 'Essikado-Ketan', 4.92, -1.74, true, false, true, 'either', 80, 20, 'Ordering is on in this constituency.'),
  ('effia', 'Western', 'Effia', 4.95, -1.77, false, false, true, 'either', 180, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('shama', 'Western', 'Shama', 5.02, -1.63, false, false, true, 'either', 120, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('mpohor', 'Western', 'Mpohor', 5.06, -1.7, false, false, true, 'either', 200, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('cape-coast-south', 'Central', 'Cape Coast South', 5.103, -1.247, false, false, true, 'either', 260, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('cape-coast-north', 'Central', 'Cape Coast North', 5.13, -1.26, false, false, true, 'either', 280, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('keea', 'Central', 'Komenda-Edina-Eguafo-Abrem', 5.08, -1.48, false, false, true, 'either', 140, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('mfantseman', 'Central', 'Mfantseman', 5.2, -1.05, false, false, true, 'either', 200, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('agona-west', 'Central', 'Agona West', 5.53, -0.7, false, false, true, 'either', 240, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('new-juaben-south', 'Eastern', 'New Juaben South', 6.094, -0.26, false, false, true, 'either', 140, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('new-juaben-north', 'Eastern', 'New Juaben North', 6.12, -0.25, false, false, true, 'either', 160, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('akuapem-north', 'Eastern', 'Akuapem North', 5.98, -0.09, false, false, true, 'either', 280, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('abuakwa-south', 'Eastern', 'Abuakwa South', 6.21, -0.45, false, false, true, 'either', 280, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('lower-manya', 'Eastern', 'Lower Manya Krobo', 6.1, 0.0, false, false, true, 'either', 260, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ho-central', 'Volta', 'Ho Central', 6.601, 0.471, false, false, true, 'either', 240, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('hohoe', 'Volta', 'Hohoe', 7.15, 0.47, false, false, true, 'either', 120, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('keta', 'Volta', 'Keta', 5.92, 0.99, false, false, true, 'either', 260, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('ketu-south', 'Volta', 'Ketu South', 6.12, 1.15, false, false, true, 'either', 220, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('south-dayi', 'Volta', 'South Dayi', 6.7, 0.3, false, false, true, 'either', 220, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('tamale-central', 'Northern', 'Tamale Central', 9.403, -0.842, false, false, true, 'either', 220, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('tamale-south', 'Northern', 'Tamale South', 9.37, -0.84, false, false, true, 'either', 180, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('tamale-north', 'Northern', 'Tamale North', 9.44, -0.85, false, false, true, 'either', 200, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('yendi', 'Northern', 'Yendi', 9.44, -0.01, false, false, true, 'either', 240, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('savelugu', 'Northern', 'Savelugu', 9.62, -0.83, false, false, true, 'either', 180, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bolgatanga-central', 'Upper East', 'Bolgatanga Central', 10.786, -0.851, false, false, true, 'either', 180, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('navrongo-central', 'Upper East', 'Navrongo Central', 10.89, -1.09, false, false, true, 'either', 280, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bawku-central', 'Upper East', 'Bawku Central', 11.06, -0.24, false, false, true, 'either', 220, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('zebilla', 'Upper East', 'Zebilla', 10.92, -0.46, false, false, true, 'either', 140, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('wa-central', 'Upper West', 'Wa Central', 10.06, -2.51, false, false, true, 'either', 260, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('nadowli-kaleo', 'Upper West', 'Nadowli Kaleo', 10.33, -2.4, false, false, true, 'either', 220, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('lawra', 'Upper West', 'Lawra', 10.65, -2.9, false, false, true, 'either', 200, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('jirapa', 'Upper West', 'Jirapa', 10.53, -2.7, false, false, true, 'either', 140, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('sunyani-east', 'Bono', 'Sunyani East', 7.335, -2.312, false, false, true, 'either', 260, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('sunyani-west', 'Bono', 'Sunyani West', 7.36, -2.38, false, false, true, 'either', 160, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('berekum-east', 'Bono', 'Berekum East', 7.45, -2.58, false, false, true, 'either', 240, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('dormaa-central', 'Bono', 'Dormaa Central', 7.27, -2.88, false, false, true, 'either', 220, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('techiman-south', 'Bono East', 'Techiman South', 7.583, -1.934, false, false, true, 'either', 120, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('techiman-north', 'Bono East', 'Techiman North', 7.64, -1.92, false, false, true, 'either', 140, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('kintampo-north', 'Bono East', 'Kintampo North', 8.06, -1.73, false, false, true, 'either', 120, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('atebubu-amantin', 'Bono East', 'Atebubu-Amantin', 7.75, -0.98, false, false, true, 'either', 180, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('asunafo-north', 'Ahafo', 'Asunafo North', 6.95, -2.35, false, false, true, 'either', 280, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('asunafo-south', 'Ahafo', 'Asunafo South', 6.75, -2.45, false, false, true, 'either', 260, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('asutifi-north', 'Ahafo', 'Asutifi North', 7.05, -2.2, false, false, true, 'either', 260, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('tano-north', 'Ahafo', 'Tano North', 7.15, -2.1, false, false, true, 'either', 280, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('sefwi-wiawso', 'Western North', 'Sefwi Wiawso', 6.217, -2.483, false, false, true, 'either', 160, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bibiani', 'Western North', 'Bibiani-Anhwiaso-Bekwai', 6.46, -2.33, false, false, true, 'either', 260, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('juaboso', 'Western North', 'Juaboso', 6.33, -2.82, false, false, true, 'either', 280, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('aowin', 'Western North', 'Aowin', 5.85, -2.8, false, false, true, 'either', 160, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('jasikan', 'Oti', 'Jasikan', 7.41, 0.46, false, false, true, 'either', 280, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('nkwanta-north', 'Oti', 'Nkwanta North', 8.26, 0.52, false, false, true, 'either', 240, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('krachi-east', 'Oti', 'Krachi East', 7.8, 0.05, false, false, true, 'either', 160, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('krachi-west', 'Oti', 'Krachi West', 7.8, -0.05, false, false, true, 'either', 240, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('damongo', 'Savannah', 'Damongo', 9.083, -1.817, false, false, true, 'either', 180, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bole', 'Savannah', 'Bole', 9.03, -2.48, false, false, true, 'either', 200, 33, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('salaga-south', 'Savannah', 'Salaga South', 8.55, -0.52, false, false, true, 'either', 140, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('sawla-tuna-kalba', 'Savannah', 'Sawla-Tuna-Kalba', 9.28, -2.42, false, false, true, 'either', 260, 41, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('nalerigu', 'North East', 'Nalerigu', 10.533, -0.367, false, false, true, 'either', 120, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('walewale', 'North East', 'Walewale', 10.35, -0.8, false, false, true, 'either', 200, 49, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('bunkpurugu', 'North East', 'Bunkpurugu', 10.51, -0.07, false, false, true, 'either', 220, 25, 'Share Bloom with people you know here. Downloads and shares are counted live.'),
  ('yunyoo', 'North East', 'Yunyoo', 10.45, -0.2, false, false, true, 'either', 260, 57, 'Share Bloom with people you know here. Downloads and shares are counted live.')
on conflict (id) do nothing;
