/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CartRouteImport } from './routes/cart'
import { Route as FloristsRouteImport } from './routes/florists'
import { Route as HqRouteImport } from './routes/hq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as HqIndexRouteImport } from './routes/hq.index'
import { Route as HqColdRouteImport } from './routes/hq.cold'
import { Route as HqCoverageRouteImport } from './routes/hq.coverage'
import { Route as HqDutyRouteImport } from './routes/hq.duty'
import { Route as HqPartnersRouteImport } from './routes/hq.partners'
import { Route as HqPricesRouteImport } from './routes/hq.prices'
import { Route as HqQueueRouteImport } from './routes/hq.queue'
import { Route as HqStaffRouteImport } from './routes/hq.staff'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const FloristsRoute = FloristsRouteImport.update({
  id: '/florists',
  path: '/florists',
  getParentRoute: () => rootRouteImport,
} as any)
const HqRoute = HqRouteImport.update({
  id: '/hq',
  path: '/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HqRoute,
} as any)
const HqColdRoute = HqColdRouteImport.update({
  id: '/cold',
  path: '/cold',
  getParentRoute: () => HqRoute,
} as any)
const HqCoverageRoute = HqCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => HqRoute,
} as any)
const HqDutyRoute = HqDutyRouteImport.update({
  id: '/duty',
  path: '/duty',
  getParentRoute: () => HqRoute,
} as any)
const HqPartnersRoute = HqPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => HqRoute,
} as any)
const HqPricesRoute = HqPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => HqRoute,
} as any)
const HqQueueRoute = HqQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => HqRoute,
} as any)
const HqStaffRoute = HqStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => HqRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/florists': typeof FloristsRoute
  '/hq': typeof HqRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/shop': typeof ShopRoute
  '/hq/cold': typeof HqColdRoute
  '/hq/coverage': typeof HqCoverageRoute
  '/hq/duty': typeof HqDutyRoute
  '/hq/partners': typeof HqPartnersRoute
  '/hq/prices': typeof HqPricesRoute
  '/hq/queue': typeof HqQueueRoute
  '/hq/staff': typeof HqStaffRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/hq/': typeof HqIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/florists': typeof FloristsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/shop': typeof ShopRoute
  '/hq/cold': typeof HqColdRoute
  '/hq/coverage': typeof HqCoverageRoute
  '/hq/duty': typeof HqDutyRoute
  '/hq/partners': typeof HqPartnersRoute
  '/hq/prices': typeof HqPricesRoute
  '/hq/queue': typeof HqQueueRoute
  '/hq/staff': typeof HqStaffRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/hq': typeof HqIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/calendar': typeof CalendarRoute
  '/cart': typeof CartRoute
  '/florists': typeof FloristsRoute
  '/hq': typeof HqRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/ops': typeof OpsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/partner': typeof PartnerRoute
  '/people': typeof PeopleRoute
  '/shop': typeof ShopRoute
  '/hq/cold': typeof HqColdRoute
  '/hq/coverage': typeof HqCoverageRoute
  '/hq/duty': typeof HqDutyRoute
  '/hq/partners': typeof HqPartnersRoute
  '/hq/prices': typeof HqPricesRoute
  '/hq/queue': typeof HqQueueRoute
  '/hq/staff': typeof HqStaffRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/hq/': typeof HqIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/calendar'
    | '/cart'
    | '/florists'
    | '/hq'
    | '/login'
    | '/onboarding'
    | '/ops'
    | '/orders'
    | '/partner'
    | '/people'
    | '/shop'
    | '/hq/cold'
    | '/hq/coverage'
    | '/hq/duty'
    | '/hq/partners'
    | '/hq/prices'
    | '/hq/queue'
    | '/hq/staff'
    | '/orders/$id'
    | '/product/$id'
    | '/hq/'
    | '/orders/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/calendar'
    | '/cart'
    | '/florists'
    | '/login'
    | '/onboarding'
    | '/ops'
    | '/partner'
    | '/people'
    | '/shop'
    | '/hq/cold'
    | '/hq/coverage'
    | '/hq/duty'
    | '/hq/partners'
    | '/hq/prices'
    | '/hq/queue'
    | '/hq/staff'
    | '/orders/$id'
    | '/product/$id'
    | '/hq'
    | '/orders'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/calendar'
    | '/cart'
    | '/florists'
    | '/hq'
    | '/login'
    | '/onboarding'
    | '/ops'
    | '/orders'
    | '/partner'
    | '/people'
    | '/shop'
    | '/hq/cold'
    | '/hq/coverage'
    | '/hq/duty'
    | '/hq/partners'
    | '/hq/prices'
    | '/hq/queue'
    | '/hq/staff'
    | '/orders/$id'
    | '/product/$id'
    | '/hq/'
    | '/orders/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CalendarRoute: typeof CalendarRoute
  CartRoute: typeof CartRoute
  FloristsRoute: typeof FloristsRoute
  HqRoute: typeof HqRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OpsRoute: typeof OpsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PartnerRoute: typeof PartnerRoute
  PeopleRoute: typeof PeopleRoute
  ShopRoute: typeof ShopRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florists': {
      id: '/florists'
      path: '/florists'
      fullPath: '/florists'
      preLoaderRoute: typeof FloristsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq': {
      id: '/hq'
      path: '/hq'
      fullPath: '/hq'
      preLoaderRoute: typeof HqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/cold': {
      id: '/hq/cold'
      path: '/cold'
      fullPath: '/hq/cold'
      preLoaderRoute: typeof HqColdRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/coverage': {
      id: '/hq/coverage'
      path: '/coverage'
      fullPath: '/hq/coverage'
      preLoaderRoute: typeof HqCoverageRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/duty': {
      id: '/hq/duty'
      path: '/duty'
      fullPath: '/hq/duty'
      preLoaderRoute: typeof HqDutyRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/partners': {
      id: '/hq/partners'
      path: '/partners'
      fullPath: '/hq/partners'
      preLoaderRoute: typeof HqPartnersRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/prices': {
      id: '/hq/prices'
      path: '/prices'
      fullPath: '/hq/prices'
      preLoaderRoute: typeof HqPricesRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/queue': {
      id: '/hq/queue'
      path: '/queue'
      fullPath: '/hq/queue'
      preLoaderRoute: typeof HqQueueRouteImport
      parentRoute: typeof HqRoute
    }
    '/hq/staff': {
      id: '/hq/staff'
      path: '/staff'
      fullPath: '/hq/staff'
      preLoaderRoute: typeof HqStaffRouteImport
      parentRoute: typeof HqRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HqRouteChildren {
  HqColdRoute: typeof HqColdRoute
  HqCoverageRoute: typeof HqCoverageRoute
  HqDutyRoute: typeof HqDutyRoute
  HqPartnersRoute: typeof HqPartnersRoute
  HqPricesRoute: typeof HqPricesRoute
  HqQueueRoute: typeof HqQueueRoute
  HqStaffRoute: typeof HqStaffRoute
  HqIndexRoute: typeof HqIndexRoute
}

const HqRouteChildren: HqRouteChildren = {
  HqColdRoute: HqColdRoute,
  HqCoverageRoute: HqCoverageRoute,
  HqDutyRoute: HqDutyRoute,
  HqPartnersRoute: HqPartnersRoute,
  HqPricesRoute: HqPricesRoute,
  HqQueueRoute: HqQueueRoute,
  HqStaffRoute: HqStaffRoute,
  HqIndexRoute: HqIndexRoute,
}

const HqRouteWithChildren = HqRoute._addFileChildren(HqRouteChildren)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CalendarRoute: CalendarRoute,
  CartRoute: CartRoute,
  FloristsRoute: FloristsRoute,
  HqRoute: HqRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OpsRoute: OpsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PartnerRoute: PartnerRoute,
  PeopleRoute: PeopleRoute,
  ShopRoute: ShopRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
